// frontend/src/pages/Home.jsx
import { Link } from "react-router-dom";
import { apiDomain } from "../helpers/apiDomain";
import useFetch from "../hooks/useFetch";
import DiscountCard from "../components/DiscountCard";
import ProductGridCard from "../components/ProductGridCard";
import ProductListCard from "../components/ProductListCard";

export default function Home() {
  const productsFeatured = useFetch(`${apiDomain.https}/api/products?tag=featured&amount=4`);
  const productsBestSeller = useFetch(`${apiDomain.https}/api/products?tag=popular&amount=9`);
  const tags = useFetch(`${apiDomain.https}/api/tags`);

  return (
    <>
      <ul className="tags-container">
        {tags?.data?.map((tag) => (
          <li key={tag}>
            <Link to={`/products?tag=${tag.toLowerCase()}`}>
              <div className="tag-wrapper">
                <div className="tag-circle"></div>
                <p>{tag}</p>
              </div>
            </Link>
          </li>
        ))}
      </ul>
      <DiscountCard />

      <section className="featured-products">
        <div className="featured-header">
          <h2>Featured products</h2>
          <Link to={"/products?tag=featured"}>view all</Link>
        </div>
        <div className="product-grid">
          {productsFeatured.data?.map((product) => (
            <ProductGridCard key={product.id} product={product} />
          ))}
        </div>
      </section>

      <section className="best-sellers">
        <div className="best-seller-header">
          <h2>Best sellers </h2>
          <Link to={"/products?tag=popular"}>view all</Link>
        </div>
        <div className="product-list">
          {productsBestSeller.data?.map((product) => (
            <ProductListCard key={product.id} product={product} />
          ))}
        </div>
      </section>
    </>
  );
}

// solid/src/pages/Home.tsx
import styles from "./Home.module.scss";
import { For, Suspense, createResource } from "solid-js";
import LoadingSpinner from "../components/LoadingSpinner";
import ProductCard from "../components/ProductCard";
import { API_URL } from "../helpers/constants";
import { A } from "@solidjs/router";

const getProducts = async (query: string) =>
  (await fetch(`${API_URL}/api/products${query}`)).json();

export default function Home() {
  const [featured] = createResource(() => getProducts("?tag=featured"));
  const [popular] = createResource(() => getProducts("?tag=popular"));

  return (
    <div class={`${styles.page} container`}>
      <section>
        <Suspense fallback={<LoadingSpinner />}>
          <header>
            <h2>Featured</h2>
            <A href="products?tag=featured">View all</A>
          </header>
          <div class={styles.gallery}>
            <For each={featured()}>
              {(product) => <ProductCard product={product} />}
            </For>
          </div>
        </Suspense>
      </section>
      <section>
        <Suspense fallback={<LoadingSpinner />}>
          <header>
            <h2>Popular</h2>
            <A href="products?tag=popular">View all</A>
          </header>
          <div class={styles.gallery}>
            <For each={popular()}>
              {(product) => <ProductCard product={product} />}
            </For>
          </div>
        </Suspense>
      </section>
    </div>
  );
}
